/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Image from 'next/image';
import Layout from './producto/layout';
import Link from 'next/link';
import { useRouter } from 'next/router';

//importar firebase
import firebaseApp from '../firebase';
import {
	getFirestore,
	collection,
	addDoc,
	getDocs,
	doc,
	deleteDoc,
	getDoc,
	setDoc,
} from 'firebase/firestore';
import { async } from '@firebase/util';
import { getStorage } from 'firebase/storage';

const db = getFirestore(firebaseApp);
const storage = getStorage(firebaseApp);

//
export default function Productos({ productos }) {
	const router = useRouter();

	return (
		<Layout>
			<Head>
				<title>CZ Productos</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='w-3/4  mx-auto mt-10'>
				<div className='w-3/4 flex flex-wrap gap-2 justify-center mx-auto'>
					{productos.map((product) => (
						<div
							className='mb-5 w-48 border-2 px-2 py-2 rounded-xl'
							key={product.id}
						>
							<div className=''></div>
							<img src={product.url} alt='img' className='rounded-lg' />
							<h5 className='text-lg font-bold mt-2'>{product.name}</h5>
							{/* <div className='text'>
								<p>{product.desc}</p>
							</div> */}
							<div className=' font-semibold'>
								<p>{product.price}€</p>
							</div>

							<button
								className='bg-brownLogo px-3 py-1 mx-auto rounded text-white  bottom-1'
								onClick={() => router.push(`/producto/${product.id}`)}
							>
								View
							</button>
						</div>
					))}
				</div>
			</div>
		</Layout>
	);
}

export const getServerSideProps = async (context) => {
	const querySnapshot = await getDocs(collection(db, 'producto'));
	const docs = [];
	querySnapshot.forEach((doc) => {
		docs.push({ ...doc.data(), id: doc.id });
	});

	return {
		props: {
			productos: docs,
		},
	};
};
