/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/Layout';
import Link from 'next/link';
import { useRouter } from 'next/router';

//importar firebase
import firebaseApp from '../firebase';
import {
	getFirestore,
	query,
	collection,
	addDoc,
	getDocs,
	doc,
	deleteDoc,
	getDoc,
	setDoc,
	where,
} from 'firebase/firestore';
import { async } from '@firebase/util';
import { getStorage } from 'firebase/storage';

const db = getFirestore(firebaseApp);
const storage = getStorage(firebaseApp);

//
export default function Productos({ productos }) {
	const router = useRouter();

	return (
		<Layout>
			<Head>
				<title>CZ Productos</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='w-3/4  mx-auto xs:mt-24 xs:w-full xs:px-3'>
				<div className='xs:w-full w-3/4 flex flex-wrap gap-2 justify-center mx-auto'>
					{productos.map((product) => (
						<div
							className='mb-5 mx-2 w-32 border-2 px-2 py-2 rounded-xl'
							key={product.id}
						>
							<div className=''></div>
							<img src={product.url} alt='img' className='rounded-lg' />
							<h5 className='text-lg font-bold mt-2 mb-1 truncate xs:text-sm'>
								{product.name}
							</h5>
							<div className=' font-semibold mb-2 xs:text-sm'>
								<p>{product.price}€</p>
							</div>

							<div className='justify-center flex '>
								<button
									className='bg-brownLogo px-3 py-1  rounded text-white  bottom-1'
									onClick={() => router.push(`/producto/${product.id}`)}
								>
									View
								</button>
							</div>
						</div>
					))}
				</div>
			</div>
		</Layout>
	);
}

export const getServerSideProps = async (context) => {
	const querySnapshot = await getDocs(collection(db, 'producto'));

	const docs = [];
	querySnapshot.forEach((doc) => {
		docs.push({ ...doc.data(), id: doc.id });
	});

	return {
		props: {
			productos: docs,
		},
	};
};
